baseURL = "https://phil-azar.com"
languageCode = "en-us"
title = "Phil Azar"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = "UA-190579681-1"

[params]
    author = "Phil Azar"
    description = "Data Scientist & Writer"
    githubUsername = "filetczar"
    accent = "DodgerBlue"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift", "python", "R"]
    ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/posts/"
    name = "Blog"
    weight = 3

[[menu.main]]
    url = "/projects/"
    name = "Projects"
    weight = 4
    
[[menu.main]]
    url = "/cheat-sheets/"
    name = "Cheat Sheets"
    weight = 5
    
# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.


[[menu.icon]]
    url = "https://github.com/filetczar/"
    name = "fab fa-github"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/filetczar/"
    name = "fab fa-twitter"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/phil-azar-87aa6779/"
    name = "fab fa-linkedin"
    weight = 3

